version: '3.8'

# This docker-compose is for development only
# For production, the docker-compose.prod.yml will be defined in portainer.io

services:

  db:
    container_name: tiktok-bot-postgres
    image: postgres:16.1-bullseye
    restart: unless-stopped
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app-network

  pgadmin:
    container_name: tiktok-bot-pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@navarrotech.net
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5051:80
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge